### ISSUE TITLE
Format CPU and Memory usage using two digits

### ISSUE THREAD

**Issue by fmonteghetti** [LGiki/gnome-shell-extension-simple-system-monitor#3]
Thanks a lot for this useful extension!

In the function extension.js::toDisplayString(), the string giving the CPU usage does not have a constant length. This means that when CPU usage crosses 10%, everything in the gnome shell top bar moves by 1 character, which can be distracting.

If you think this is worth fixing, I suggest the attached patch that introduces a function formatUsageVal() that relies on padStart() to provide a string with constant width. I have been using it without issue on 41.3.

[patch.txt](https://github.com/LGiki/gnome-shell-extension-simple-system-monitor/files/8104385/patch.txt)

The documentation for padStart() can be found here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

**Comment by LGiki** [comment]
Thanks a lot, this is a very useful patch, I will update the extension and apply it.

**Comment by LGiki** [comment]
Thanks a lot for your suggestion, I have updated the extension.
Filling 0 in front of usage value seems a bit strange, so I changed to filling spaces in front of usage value, but there are still issues that cause distraction when using variable-width fonts, because in variable-width fonts, spaces and numbers do not have the same width. So I added a setting for customize display font, when it is set to [monospaced font](https://en.wikipedia.org/wiki/Monospaced_font), the problem was solved and the extension works fine. As this screenshot shows:
![GIF 2022-2-24 9-53-02](https://user-images.githubusercontent.com/20807713/155483262-debd5226-180e-4bc0-9b68-2d5caf4d81ad.gif)

---

If you prefer to fill 0, you can modify the parameters of `padStart()` in these two places:
https://github.com/LGiki/gnome-shell-extension-simple-system-monitor/blob/7bccbd05f472b1346d48aa39570121f548cb9003/src/extension.js#L254
https://github.com/LGiki/gnome-shell-extension-simple-system-monitor/blob/7bccbd05f472b1346d48aa39570121f548cb9003/src/extension.js#L259
